### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wiserweb**
Added instructions on how to fix the issue caused by new Perl SSL verification baseline security.

Added note to users of VMWare Workstation regarding ovftool.

### CODE REVIEW

**Comment by steadfasterX** [comment]
many thanks for your pull request! 
Unfortunately I cannot (fully) accept it due to the following:

Regarding the self-signed cert prob (great to see that you have identified this):
The ssl perl check for self signed certs was fixed for a while but it may occur again. But I would better like to fix this like before so no instructions are needed. SSL_verify_mode should be set the same way as we do already for PERL_LWP_SSL_VERIFY_HOSTNAME. Seems to be pretty straight forward.
I can not test it but I would do it the same way like with the mentioned variable. Could you try that?
(affect 3 files: etc/sysvars_vEMan.cfg, ./libs/runFUNCTION.vEMan, ./vEMan)
I can prepare that, too but it may take a while.
If you can do: Please create a new pull request!

Regarding VMware Workstation:
Nice catch btw. Well I would prefer to give a hint to the user at the end that he can still install a valid ovftool version by just changing the variable in etc/uservars_vEMan.cfg to the valid one.
If you want to update: Please create a new pull request!

**Comment by steadfasterX** [comment]
see above comment (https://github.com/xdajog/vEMan/pull/1#issuecomment-123803311)

**Comment by wiserweb** [comment]
Ok, no problem. The solution I initially submitted was not entirely complete, the pull request was premature and I was going to message you today about not accepting the pull :)

I have found another solution that resolves the issue without touching perl which I think you will love since it will resolve all similar issues.

What worked was editing the VICommon.pm file.. the link to the pastebin is not my solution as I cannot attest that it will also work with IP only connection. The concept is the same. I will send you my working VICommon.pm code when I get to that machine.

http://pastebin.com/Kt4jXV9d

It seems almost everyone is having problems connecting via CLI even without vEMan. This is where I found the information in the vmware forum. The link is on the other machine. I will send the link as well.

Regarding ovftool I leave it in your hands. Good to give hints, but also good to inform the people in the readme.

**Comment by wiserweb** [comment]
As discussed, using only an IP address the latest release does not connect.

This following workaround is certified to work with either hostname or IP which utilizes a self-signed certificate.

These changes need to be applied three times in the VICommon.pm file.

This file is located: /usr/share/perl/5.18.2/VMware/VICommon.pm 

## Before

   my $user_agent = LWP::UserAgent->new(agent => "VI Perl");
   my $cookie_jar = HTTP::Cookies->new(ignore_discard => 1);
   $user_agent->cookie_jar( $cookie_jar );
   $user_agent->protocols_allowed( ['http', 'https'] );

## After

   my $user_agent = LWP::UserAgent->new(agent => "VI Perl");
   my $cookie_jar = HTTP::Cookies->new(ignore_discard => 1);
   $user_agent->cookie_jar( $cookie_jar );
   $user_agent->protocols_allowed( ['http', 'https'] );
  $user_agent->ssl_opts('verify_hostname' => 0);
  $user_agent->ssl_opts('SSL_verify_mode' => 0);

Simply search in the file for the three instances of ' my $user_agent = LWP::UserAgent' and modify each code block as the example above.

Save the changes and you will be able to connect with vEMan.

**Comment by steadfasterX** [comment]
Thanks again! 
I highly prefer a solution which works transparent - out of the box. Your solution is a client site change which is not desirable for vEMan. It is hard enough to get it installed because of so many (mostly perl) issues that I do not want to let the user edit perl standard files. What would happen after an perl update - let me say in 7 months? vEMan suddenly would stop working and the user needs to remember that change and do it again.. :(

The first question is, is the following line really needed in **vEMan** (! not at the CLI --> **there** you **will** need it !) or does it works without?

> $user_agent->ssl_opts('verify_hostname' => 0);

The reason why I ask: This setting shouldn't be needed because vEMan uses the following variable when connecting `PERL_LWP_SSL_VERIFY_HOSTNAME=0`. This has/should have the same effect then adding the above line - therefore shouldn't being needed when using vEMan.

I use it like described here: https://communities.vmware.com/thread/240659?start=20
You can see it's implementation in vEman here: [search results in vEMan code for this](https://github.com/xdajog/vEMan/search?utf8=%E2%9C%93&q=PERL_LWP_SSL_VERIFY_HOSTNAME&type=Code)

The second line is what I'm not sure about:

>  $user_agent->ssl_opts('SSL_verify_mode' => 0);

The problem with that is that this option seems to be deprecated: [source](https://communities.vmware.com/thread/428588?tstart=0) 
Some link directs me to the option to set the CA file variable but I'm not sure if that would work. I [catch the certificate already](https://github.com/xdajog/vEMan/blob/master/etc/sysvars_vEMan.cfg#L35) so this is already there but .. well I have somehow not a good feeling with that (if it even works, of course): [HTTPS_CA](http://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.vcli.getstart.doc%2Fcli_install.4.10.html&resultof=%22HTTPS_CA%22). But at the end that seems to be the only available solution - if it works.

Regarding Perl LWP this will guide us to the [ssl_opts](http://search.cpan.org/~ether/libwww-perl-6.13/lib/LWP/UserAgent.pm#%24ua-%3Essl_opts). That means we would need to set `PERL_LWP_SSL_CA_FILE` and `PERL_LWP_SSL_CA_PATH` to get it work.
See also here: [stackoverflow (tries the other way around but you will see the details](http://stackoverflow.com/questions/74358/how-can-i-get-lwp-to-validate-ssl-server-certificates#5329129).

At the end I see it again: using perl as a SDK is a nightmare. I read in the last 60 minutes a lot about people having problems with ssl and perl and lwp which all together can be totally different depending on what version of the relevant modules you have installed.
It also depends if you still having the "deprecated" module there or the new one because if you still using the old one the current setup in vEMan will be enough and if using the new way of ssl in perl the CA things may hopefully fix that. So we need both in vEMan, of course.

There are major changes in LWP 6 which causes those problems mainly but whrrrr.. I really hate all that perl issues ;) sorry to all the perl guru's - just my opinion ;)

**Comment by wiserweb** [comment]
Confirmed it works with only adding this line at LWP instantiation.

$user_agent->ssl_opts('SSL_verify_mode' => 0);

Commenting the line gives error:

Server version unavailable at 'https://10.10.10.10:443/sdk/vimService.wsdl' at /usr/share/perl/5.18/VMware/VICommon.pm line 554.

Try to start vEMan v1.0.4_PREVIEW for Linux at the commandline to see debug output

**Comment by steadfasterX** [comment]
ok thx for feedback. I need to sort out what environment variable would set ssl_verify_mode to 0 and it should be working without any code change on perl site.

**Pull request closed without merging**
